parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     silversmoke
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       smtp.alwaysdata.com
    mailer_user:       contact@getsilversmoke.com
    mailer_password:   silver1956

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
