svk_welcome_homepage:
    pattern:  /
    defaults: { _controller: SvkWelcomeBundle:Welcome:index }

svk_welcome_subscribe:
    pattern:  /subscribe
    defaults: { _controller: SvkWelcomeBundle:Welcome:subscribe }

svk_welcome_subscribed:
    pattern:  /subscribed
    defaults: { _controller: SvkWelcomeBundle:Welcome:success }

svk_welcome_about:
    pattern: /about
    defaults: {_controller: SvkWelcomeBundle:Welcome:about }
svk_welcome_faq:
    pattern: /faq
    defaults: {_controller: SvkWelcomeBundle:Welcome:faq }
svk_welcome_contact:
    pattern: /contact
    defaults: {_controller: SvkWelcomeBundle:Welcome:contact }
svk_welcome_contact_form:
    pattern: /contact/form
    defaults: {_controller: SvkWelcomeBundle:Welcome:contactForm }
