svk_welcome_homepage:
    pattern:  /
    defaults: { _controller: SvkWelcomeBundle:Welcome:index }

svk_welcome_subscribe:
    pattern:  /subscribe
    defaults: { _controller: SvkWelcomeBundle:Welcome:subscribe }

svk_welcome_subscribed:
    pattern:  /subscribed
    defaults: { _controller: SvkWelcomeBundle:Welcome:success }
