parameters:
#    svk_welcome.example.class: Svk\WelcomeBundle\Example

services:
#    svk_welcome.example:
#        class: %svk_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
